// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpzwzmtuujtsiibgzyfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwend6bXR1dWp0c2lpYmd6eWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3OTY5MjksImV4cCI6MjA3NTM3MjkyOX0.3PEbDW4lAc9moJF6saDNgtaK2C2nd0Q--Lt029LelEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});